<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="libs\*.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Gui\Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ncmod.json" LogicalName="ncmod.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="icon.png" LogicalName="icon.png" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NetCraft.Test" />
  </ItemGroup>

  <Target Name="DeployModToHosts" AfterTargets="Build" Condition="'$(ModHostDirs)' != ''">
    <ItemGroup>
      <ModHostDir Include="$(ModHostDirs)" />
    </ItemGroup>
    <MakeDir Directories="@(ModHostDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="%(ModHostDir.Identity)" SkipUnchangedFiles="true" />
  </Target>

</Project>
